### ISSUE TITLE
Language Controller breaks CSS

### ISSUE THREAD

**Issue by Alletkla** [StEx2022-23/sql2regex#13]
![image](https://user-images.githubusercontent.com/65451851/167655807-2021ac2d-3d1c-48e3-b5a8-1d6bd3898cb9.png)
![image](https://user-images.githubusercontent.com/65451851/167655831-7e3716a6-9af6-4764-b6c1-79107553c6ae.png)

**Comment by binkertpat** [comment]
i wasnt able to reproduce / trigger the error .. in my current branch, cloned from main today, is everything thine
