### ISSUE TITLE
UserProp/PropertyManager/-MapBuilder interaction

### ISSUE THREAD

**Issue by Alletkla** [StEx2022-23/sql2regex#25]
When Using UserPropertys in Deparser it is not possible to get an desired Property/ RegExGenerator cause UserProp has no functionality for it.

PropertyManager: Property Interface is returned, but RegEx Generator is need for usage in the Deparsers.

What To Do?

- Let RegExGenerator implement Property?
- rename getPropertyByPropOption and getPropertyByClass to getRegExGeneratorBy .... ?
- let PropertyManager save the instance of UserProperty and return from it, instead of the defualt map if set?
- include GetRegExGeneratorBy in UserProperty?

or sounds best to me (that not every class has to be changed, since PropertyMapBuilder also just returns Properties MapValues and no RegExGeneratorInterface Map Values):
- Let Property interface extend RegExGenerator Interface (let it open, that other Generators or whatever can be added and nicely structured and still be extended by the Big Property infterface that is used in the Maps and Builders?

**Comment by binkertpat** [comment]
We can do what u describe last.. Property extends RegExGen. But then is the Question, isnt it possible to connect these interfaces? Something like interface Property<T, S> with: Set<T> getSettings(), String genRegEx(S value), void setCapturingGroup(boolean capturingGroup);

This is what i would prefer.
