### ISSUE TITLE
How to handle non zero padded dates

### ISSUE THREAD

**Issue by Alletkla** [StEx2022-23/sql2regex#4]
for empty SynonymManager:
`Assertions.assertEquals("2012-05-06", dateValueSynonymManager.generateSynonymRegexFor(new DateValue("{2012-5-6}")));`

DateValue always converts into zero padded date. 
So: A teacher unchecking all alternative formats and inserting 2012-5-6 would get a RegEx String part of 2012-05-06

DateValue has no Option "getRaw()" as TimeStampValue has.

Problem or not?

**Comment by binkertpat** [comment]
I fix it's a problem. If the teacher insert it that way, you can assume, that he teached this that way. My first idea was, that the zero pads for months and days are optional in the regex? Like: 2012-0?5-0?6

**Comment by Alletkla** [comment]
atm thats not possible. Cause Dates are automatically converted into an Date-Object. 
atm this is only a Problem when no pattern is checked, cause the non zero padded pattern will be included in the SynonymGenerator

**Comment by Alletkla** [comment]
possible Solutions:

- [ ]  accept it, cause it isn't changeable without modifying the jsqlParserCode
- [ ] modify the jsqlParserCode (add rawValue for DateValue), what happens to license? @binkertpat

**Comment by binkertpat** [comment]
I would accept it bc by modifying licence problems will come up.. but we have to document it
