### ISSUE TITLE
No Escapes in Order by Deparser

### ISSUE THREAD

**Issue by Alletkla** [StEx2022-23/sql2regex#50]
+ will it be possible to use alias in ORDER BY, HAVING and GROUP BY?

SELECT SUM(col1) as s1 FROM table1 ORDER BY SUM(col1)
→

^(?:SELECT|ELECT|SLECT|SEECT|SELCT|SELET|SELEC)\s+(?:(?:SUM|SUMME)\s*\(\s*(?:col1|ol1|cl1|co1|col)\s*\)\s*\s*(?:(?:ALIAS|LIAS|AIAS|ALAS|ALIS|ALIA)|(?:AS|S|A))\s+s1)\s+(?:FROM|ROM|FOM|FRM|FRO)\s+(?:table1|able1|tble1|tale1|tabe1|tabl1|table)(\s*(?:(?:ALIAS|LIAS|AIAS|ALAS|ALIS|ALIA)|(?:AS|S|A))?\s+.*)?\s+(?:ORDER|RDER|ODER|ORER|ORDR|ORDE)\s+(?:(?:SIBLINGS|IBLINGS|SBLINGS|SILINGS|SIBINGS|SIBLNGS|SIBLIGS|SIBLINS|SIBLING)\s+)?(?:BY|Y|B)\s+(?:(?:SUM(col1)|UM(col1)|SM(col1)|SU(col1)|SUMcol1)|SUM(ol1)|SUM(cl1)|SUM(co1)|SUM(col)|SUM(col1))$

![image](https://user-images.githubusercontent.com/65451851/170833937-05a09701-6249-4f6c-a84f-91dbeaa7b04d.png)

**Comment by binkertpat** [comment]
Sänks

**Comment by binkertpat** [comment]
not only none escaping was the problem, also no support for aggregate function lang -> fixed now
