### ISSUE TITLE
WHERE BooleanField = true equals WHERE BooleanField

### ISSUE THREAD

**Issue by binkertpat** [StEx2022-23/sql2regex#76]

**Comment by Alletkla** [comment]
Add this synonym in expression Deparser

**Comment by Alletkla** [comment]
![image](https://user-images.githubusercontent.com/65451851/172375993-99c7e9d7-7bc9-4599-9e07-d93ba17c81cc.png)
 
 that way? @binkertpat

**Comment by binkertpat** [comment]
very pretty is accepted that way @Alletkla
